use bao_dien_tu;

CREATE TABLE USER_COMMENT_LOG (
    ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER INT,
    COMMENT_DATE DATE,
    COMMENT_COUNT INT,
    UNIQUE (ID_USER, COMMENT_DATE)
);

DELIMITER $$
CREATE TRIGGER TrackUserComments
AFTER INSERT ON COMMENT
FOR EACH ROW
BEGIN
    DECLARE comment_count INT;
    
    -- Kiểm tra xem user đã có bản ghi nào cho ngày hôm nay chưa
    SELECT COMMENT_COUNT INTO comment_count
    FROM USER_COMMENT_LOG
    WHERE ID_USER = NEW.NGUOI_COMMENT AND COMMENT_DATE = CURDATE();
    
    -- Nếu chưa có, tạo mới bản ghi
    IF comment_count IS NULL THEN
        INSERT INTO USER_COMMENT_LOG (ID_USER, COMMENT_DATE, COMMENT_COUNT)
        VALUES (NEW.NGUOI_COMMENT, CURDATE(), 1);
    ELSE
        -- Nếu đã có, cập nhật số lượng bình luận
        UPDATE USER_COMMENT_LOG
        SET COMMENT_COUNT = COMMENT_COUNT + 1
        WHERE ID_USER = NEW.NGUOI_COMMENT AND COMMENT_DATE = CURDATE();
    END IF;
END$$

DELIMITER ;

INSERT INTO USER_COMMENT_LOG (ID_USER, COMMENT_DATE, COMMENT_COUNT)
VALUES (1, '2024-10-22', 1);
SELECT * FROM USER_COMMENT_LOG;

-- create index
CREATE INDEX idx_post_title ON POST (TIEU_DE);
