USE BAO_DIEN_TU;

SELECT * FROM POST;

SELECT * FROM MANAGERS;

SELECT * FROM POST
WHERE LUOT_XEM > 20;

SELECT * FROM POST
WHERE XET_DUYET = '1'
order by TIEU_DE;

SELECT C.NGUOI_COMMENT, U.ACCOUNT_NAME, C.NOI_DUNG FROM COMMENT C
LEFT JOIN USERS U ON C.NGUOI_COMMENT = U.ID_USER
ORDER BY C.NGUOI_COMMENT;

SELECT * FROM POST
WHERE NOI_DUNG LIKE 'N%';
