-- DROP DATABASE BAO_DIEN_TU;
-- create database bao_dien_tu
-- CHARACTER SET utf8mb4
-- COLLATE utf8mb4_unicode_ci;
use bao_dien_tu;

CREATE TABLE MANAGERS (
	ID_MNG INT auto_increment PRIMARY KEY ,
	TEN VARCHAR(400),
	NAM_SINH YEAR 
);

CREATE TABLE REPOSTER (
	ID_REPOSTER INT auto_increment PRIMARY KEY,
	TEN VARCHAR(300) NOT NULL,
	NAM_SINH YEAR ,
	TO_CHUC VARCHAR(300) 
);

CREATE TABLE USERS (
	ID_USER INT auto_increment PRIMARY KEY ,
	ACCOUNT_NAME VARCHAR(400) NOT NULL,
	PASSWORDS INT NOT NULL,
	FACEBOOK_USER VARCHAR(400) ,
	EMAIL_USER VARCHAR (400),
    ID_MNG INT,
	FOREIGN KEY (ID_MNG) REFERENCES MANAGERS(ID_MNG)
);

CREATE TABLE POST (
	ID_POST INT auto_increment PRIMARY KEY ,
	TIEU_DE VARCHAR(400) NOT NULL,
	NOI_DUNG TEXT NOT NULL,
	IMAGES LONGBLOB,
	LUOT_XEM INT,
	XET_DUYET BIT NOT NULL,
	THOI_GIAN_DANG DATETIME ,
    NGUOI_DUYET INT,
    NGUOI_DANG INT,
	FOREIGN KEY (NGUOI_DUYET) REFERENCES MANAGERS(ID_MNG) ,
	FOREIGN KEY (NGUOI_DANG) REFERENCES REPOSTER(ID_REPOSTER)
);
CREATE TABLE SHARE (
	ID_SHARE INT auto_increment PRIMARY KEY ,
	TIME_SHARE DATETIME ,
    NGUOI_SHARE INT,
	FOREIGN KEY (NGUOI_SHARE) REFERENCES USERS(ID_USER) 
);

CREATE TABLE COMMENT (
	ID_COMMENT INT auto_increment PRIMARY KEY,
	TIME_COMMENT DATETIME ,
	NOI_DUNG TEXT ,
    NGUOI_COMMENT INT,
	FOREIGN KEY (NGUOI_COMMENT) REFERENCES USERS(ID_USER)
);

CREATE TABLE COMMENT_POST (
	ID_COMMENT_POST INT auto_increment primary key,
	ID_COMMENT INT NOT NULL, 
	ID_POST INT NOT NULL ,
	TIEU_DE VARCHAR(400),
	FOREIGN KEY (ID_COMMENT) REFERENCES comment(ID_COMMENT),
	FOREIGN KEY (ID_POST) REFERENCES post(ID_POST)
 );

CREATE TABLE SHARE_POST(
	ID_SHARE_POST INT auto_increment primary key,
	ID_SHARE INT  NOT NULL,
	ID_POST INT  NOT NULL,
	TIEU_DE VARCHAR(400),
	FOREIGN KEY (ID_SHARE) REFERENCES share(ID_SHARE),
	FOREIGN KEY (ID_POST) REFERENCES post(ID_POST)
);