@startuml sequence_sample
skinparam SequenceMessageAlignment center
actor Admin
boundary FormMenu as Foo
control MenuController as Foo1
entity MenuService as Foo2
' participant Database as Foo3
database Database as Foo3
Admin ++
autonumber 1
Admin -> Foo ++: Enter info
Admin -> Foo : Click button "Save"
Foo -> Foo : check Validate
Foo -> Foo1 ++: SaveMenu()
Foo1 -> Foo1 : check infomation
Foo1 -> Foo2 ++: saveMenu()
Foo2 -> Foo3 ++: Load(sql)
Foo3  --> Foo2 --:
Foo2 --> Foo1 --: Return
Foo1 --> Foo --: Return Notification
Foo --> Admin --: Notification
@enduml